### ISSUE TITLE
Faked delegates with in parameters don't honor the read-only semantics

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1388]
Reported by @zvirja https://github.com/FakeItEasy/FakeItEasy/issues/1338#issuecomment-402251902

Faked delegates with `in` parameters don't honor the read-only semantics of `in`, i.e. it's possible to configure the faked delegate to mutate the parameter:

```csharp
delegate void Foo(in int x);
...
var foo = A.Fake<Foo>();
A.CallTo(() => foo(A<int>.Ignored)).AssignsOutAndRefParameters(123);
int z = 0;
foo(z);
Console.WriteLine(z); // Should print 0, but prints 123
```

**Comment by thomaslevesque** [comment]
In fact, the problem isn't just for delegates. The same issue exists for normal methods:

```csharp
public interface IFoo
{
    void Bar(in int x);
}

var foo = A.Fake<IFoo>();
A.CallTo(() => foo.Bar(A<int>.Ignored)).AssignsOutAndRefParameters(123);
int z = 0;
foo.Bar(z);
Console.WriteLine(z); // Should print 0, but prints 123
```

**Comment by zvirja** [comment]
@thomaslevesque Issue shouldn't happen for the latest `Castle.Core` as it prevents you from assigning read-only parameters: https://github.com/castleproject/Core/pull/370

I'd expect that Fake shouldn't have any special handling for the "regular" proxies. At least that's so for the NSubstitute - we get that automatically 😉

**Comment by thomaslevesque** [comment]
@zvirja are you sure? The latest FakeItEasy uses Castle.Core 4.3.1, which contains this change, but I still reproduce the problem. I'll have to look into it.

Anyway, we don't use Castle.Core for delegates, so we'll have to make a specific fix for that.

**Comment by zvirja** [comment]
@thomaslevesque Yes. See [this](https://github.com/nsubstitute/NSubstitute/blob/daeec390fc3fcee2010937be05f922aa668add71/tests/NSubstitute.Acceptance.Specs/FieldReports/Issue378_InValueTypes.cs#L56) test for instance. All I had to do is to reference the newer `Castle.Core` version (for delegates extra code was required). I see that issue indeed happens for the Fake and I'm really curios about the reason 😮 

-----

The very strange this is that for .NET Framework you embed the `Castle.Core` inside. I've just checked dll file from the v4.7.0 and found that Castle is not updated there:

![image](https://user-images.githubusercontent.com/1074182/42269687-80d7bace-7f87-11e8-8cd1-0ab278f46bca.png)

Now compare the code with this actual one:

https://github.com/castleproject/Core/blob/f84d4fcebdc66b859c321b2eee5434aa41df19f5/src/Castle.Core/DynamicProxy/Generators/GeneratorUtil.cs#L27-L44

As you can see, the whole `IsReadOnly` part is gone. Likely, you embed the wrong assembly version.

I'd suggest to not embed the `Castle.Core` at all and use it as a dependency. This way clients will have a way to update the library without waiting for the Fake update.

**Comment by blairconrad** [comment]
@zvirja, you ware of course right. We are not including the proper Castle.Core _for .NET Framework builds_. I updated the version only for .NET Standard 1.6:

https://github.com/FakeItEasy/FakeItEasy/blob/c40c8fdbaf0b98c660c19bbae84881ca5112263f/src/FakeItEasy/FakeItEasy.csproj#L41-L57

```xml
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard1.6'">
    <PackageReference Include="Castle.Core" Version="4.3.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="1.0.0" />
    <PackageReference Include="System.Collections.Concurrent" Version="4.3.0" />
    <PackageReference Include="System.Runtime.Loader" Version="4.0.0" />
  </ItemGroup>

  <!-- .NET 4.5 -->

  <PropertyGroup Condition="'$(TargetFramework)' == 'net45'">
    <DefineConstants>$(DefineConstants);FEATURE_BINARY_SERIALIZATION;FEATURE_REFLECTION_GETASSEMBLIES</DefineConstants>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net45'">
    <PackageReference Include="ILMerge" Version="2.14.1208" PrivateAssets="all" />
    <PackageReference Include="Castle.Core" Version="4.2.1" PrivateAssets="all" />
  </ItemGroup>
```

.NET 4.0 is similar to 4.5. As I sit here, I'm wondering why we're duplicating that `PackageReference` at all…

**Comment by blairconrad** [comment]
@zvirja said:

> Just tested the latest `FakeItEasy` using netcoreapp runtime - everything works perfectly there for interfaces 😉 So the issue is indeed .NET Framework specific.

Okay. I'm confused. I wrote this spec:

```c#
public interface IInParam
{
    int Foo(in int x);
}

[Scenario]
public void SettingInParam(IInParam fake, int argument)
{
    "Given a fake with a method that takes an 'in' parameter"
        .x(() => fake = A.Fake<IInParam>());

    "And the 'in' argument has a known value"
        .x(() => argument = 17);

    "And a call to this method is configured to set a new value for the parameter"
        .x(() => A.CallTo(() => fake.Foo(A<int>._)).AssignsOutAndRefParameters(19));

    "When the method is called"
        .x(() => fake.Foo(in argument));

    "Then the 'in' argument retains its original value"
        .x(() => argument.Should().Be(17));
}
```

And it fails on all platforms: .NET Framework _and_ .NET Core.

**Comment by zvirja** [comment]
@blairconrad Thanks for chiming in and for the analysis.

> Okay. I'm confused. 

I used the following test project. It could happen I dome something wrong: [FakeReadOnlyTest.zip](https://github.com/FakeItEasy/FakeItEasy/files/2162963/FakeReadOnlyTest.zip)

> I'd suggest to not embed the Castle.Core at all and use it as a dependency. This way clients will have a way to update the library without waiting for the Fake update.

Isn't it simpler to consider this way for the future? 😉

**Comment by blairconrad** [comment]
Thanks for the test, @zvira. If I `dotnet test` your project, I find the same result you do.
_If I copy it into our Spec project, it fails under both platforms!_

I am incredibly confused. And nearly late for work. I'll have to leave this for a bit.

**Comment by zvirja** [comment]
> I am incredibly confused. And nearly late for work. I'll have to leave this for a bit.

I'd suggest to make a debug build and debug the following code lines:
https://github.com/castleproject/Core/blob/f84d4fcebdc66b859c321b2eee5434aa41df19f5/src/Castle.Core/DynamicProxy/Generators/GeneratorUtil.cs#L27-L44

The answer should be somewhere there.

**Comment by thomaslevesque** [comment]
@blairconrad what are you confused about? The problem seems clear to me. Castle.Core was only updated for netstandard1.6, not for net40/net45. Changing this should fix the issue. BTW, we should probably consider declaring the version of Castle.Core in a single place (e.g. Directory.Build.props) to avoid this issue in the future.

**Comment by thomaslevesque** [comment]
> I'd suggest to not embed the Castle.Core at all and use it as a dependency. This way clients will have a way to update the library without waiting for the Fake update.

This is something we began to [discuss](https://github.com/FakeItEasy/FakeItEasy/issues/1258) a while ago, without reaching a definitive conclusion. There are arguments for and against it.

**Comment by blairconrad** [comment]
@thomaslevesque, I'm confused because locally, I updated Castle.Core to 4.3.1 for .NET Standard 1.6, .NET Framework 4.5, and .NET Framework 4.0. My Spec still fails. On all 2 platforms (we don't test against 4.0). As does @zvirja's test when I copy it into our Specs project.

I'm all for changing the version of Castle.Core in one place, but thought that the presence of the `PrivateAssets="all"` for .NET Framework 4.0 and 4.5 but not .NET Standard 1.6 was the reason we had to keep explicit references.

**Comment by blairconrad** [comment]
… and I took a second and added my Spec changes to the copy at work (and updated Castle.Core to 4.3.1 for .NET Framework 4.*) and everything passes. Without changing Castle.Core version, only the .netcoreapp1.0 spec passes. This is exactly what I would expect.
But does not match the behaviour I saw at home. I'm afraid of my home setup now.

**Comment by blairconrad** [comment]
For discussion/examination, opened #1389.
As you can see, it currently fails on the `in` parameters passed to a delegate.

**Comment by thomaslevesque** [comment]
> I'm all for changing the version of Castle.Core in one place, but thought that the presence of the `PrivateAssets="all"` for .NET Framework 4.0 and 4.5 but not .NET Standard 1.6 was the reason we had to keep explicit references.

Yes, but we can keep the `PackageReference`s in the project and share just the version in Directory.Build.props, i.e.

```xml
<CastleCoreVersion>4.3.1</CastleCoreVersion>
```
```xml
<PackageReference Include="Castle.Core" Version="$(CastleCoreVersion)" />
```

**Comment by blairconrad** [comment]
The things I learn!

**Comment by blairconrad** [comment]
Regarding my weird results (failures even for faked interfaces): I ended up upgrading Visual Studio (I was on 15.5.something?) and now have a build that is no more sad than AppVeyor's!

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.7.1](https://github.com/FakeItEasy/FakeItEasy/releases/4.7.1).

Thanks for your help, @zvirja! Look for your name in the release notes. 🏆

**Comment by zvirja** [comment]
@blairconrad Thanks for mentioning, was happy to help :relaxed:
